@startuml "Modelo Entidad Relacion""

entity Movie{
    code varchar(10)<<PK>>
    name varchar(100)<<NN>>
    image varchar(225)
    year int(4)
    rating float(8)

}
Entity  Review{
    id int(8)  <auto increment> <<PK>>
    name varchar(100)<<NN>>
    email varchar(100)<<NN>>
    description varchar(4000)<<NN>>
    rating int(1)<<NN>>



}
Movie ||--o{Review

@enduml